### PR TITLE
allow opt-out of full error reporting

### PR DESCRIPTION
**Pull request by shackbarth**
see https://github.com/balderdashy/sails/issues/4606

### CODE REVIEW

**Comment by mikermcneil** [comment]
https://github.com/balderdashy/sails/issues/4606#issuecomment-482717779

@shackbarth What do you reckon?

I think it would mean we should implement this at a higher level  (probably in Waterline, in the code where we deal with errors from the db over in [forge-adapter-error](https://github.com/balderdashy/waterline/blob/3326984f0355f6d568f61920f0c11bf51e0faa4a/lib/waterline/utils/query/forge-adapter-error.js))

**Comment by mikermcneil** [comment]
I'm thinking we'd specifically rip out `meta.url`, if it exists:

image

**Comment by mikermcneil** [comment]
Not 100% what I suggested above would work exactly- but that's the direction I think we ought to explore.  That way, we improve the behavior by default rather than messing around with another config setting or env var that we have to maintain.

Also worth mentioning, I made an effort to make sure this won't happen in the new [sails-sql adapter](https://npmjs.com/package/sails-sql)  (though postgresql support is not finished there yet, so that wouldn't help you right away)

**Comment by shackbarth** [comment]
Yes, I'd definitely prefer for that output to be suppressed in every circumstance, without the need to fuss with env vars or any other sort of config. I was just being modest about breaking people's existing stuff. 

But sure, If I were king for the day I'd say that preventing this potential password leak by default is important enough to outweigh anyone's workflow that might somehow be reliant on picking this output out.

And as to implementing it at a higher level: sounds good. I only proposed the fix here because this is where the trail led me. Waterline does sound like a more sensible place to put it.

**Pull request closed without merging**
